In [ ]:
import numpy as np
import random
import scipy.stats as sps
import cv2


Задание 1
В первой задаче вам предлагается перемножить две квадратные матрицы двумя способами -- без использования пакета numpy и с ним.

In [ ]:
# Для генерации матриц используем фукнцию random -- она используется для генерации случайных объектов
# функция sample создает случайную выборку. В качестве аргумента ей передается кортеж (i,j),
# здесь i -- число строк, j -- число столбцов.
a = np.random.sample((100, 100))
b = np.random.sample((100, 100))
# выведите размерность (ранг) каждой матрицы с помощью функции ndim.
# Используйте функцию shape, что она вывела?
# ========
print("ранг a =",a.ndim, "\nранг b =", b.ndim)
print("размер матрицы a =",a.shape,"\nразмер матрицы b =",b.shape)
# ========
print(a)
print(b)

ранг a = 2 
ранг b = 2
размер матрицы a = (100, 100) 
размер матрицы b = (100, 100)
[[0.98236137 0.23291761 0.83705337 ... 0.70058802 0.99355693 0.65127551]
 [0.75031651 0.75293431 0.90620553 ... 0.40635258 0.54715149 0.13216824]
 [0.98871681 0.0368138  0.16717766 ... 0.33178454 0.75679776 0.71081958]
 ...
 [0.52712905 0.65624074 0.40426488 ... 0.47332712 0.00707499 0.60568719]
 [0.63531495 0.07769356 0.61611436 ... 0.06808461 0.26980894 0.82356663]
 [0.6453263  0.33649276 0.60721617 ... 0.2093857  0.28225224 0.33709485]]
[[0.44881748 0.68035463 0.5588062  ... 0.59570256 0.1821365  0.90176366]
 [0.83404826 0.13227429 0.25723323 ... 0.14945622 0.67296861 0.808834  ]
 [0.62188755 0.0300838  0.96410404 ... 0.22478562 0.98628938 0.57902747]
 ...
 [0.11052395 0.16993517 0.60374032 ... 0.92075419 0.29926485 0.91926712]
 [0.15888424 0.39214165 0.09195356 ... 0.88001174 0.73177381 0.95822086]
 [0.83267728 0.89557233 0.6744244  ... 0.01419058 0.0169397  0.04383652]]


In [ ]:
def mult(a, b):
    if len(a[0]) != len(b):
        raise ValueError("Неправильные размеры матриц для умножения")
    result = [[0 for _ in range(len(b[0]))] for _ in range(len(a))]
    result = [
    [sum(a[i][k] * b[k][j] for k in range(len(b))) for j in range(len(b[0]))]
    for i in range(len(a))
]

    return result

С numpy

In [ ]:
import numpy as np

def np_mult(a, b):
    result = np.dot(a, b)
    return result


In [ ]:
%%time
# засечем время работы функции без NumPy
M1 = mult(a, b)

CPU times: user 712 ms, sys: 1.2 ms, total: 713 ms
Wall time: 721 ms


In [ ]:
%%time
# засечем время работы функции с NumPy
M2 = np_mult(a, b)

CPU times: user 1.14 ms, sys: 1.9 ms, total: 3.04 ms
Wall time: 6.44 ms


In [ ]:
# проверим корректность
np.abs(np.array(M1) - M2).sum()

1.5280221532520954e-11

Задание 2
Вам подаются на вход два вектора a и b в трехмерном пространстве. Заполните их случайными числами. Реализуйте их скалярное произведение с помощью NumPy и без. Засеките время работы, как это показано в заданиях выше.

In [ ]:
a = np.random.sample((1, 3))
a = list(a)[0]
b = np.random.sample((1, 3))
b = list(b)[0]
print(a, b)

[0.78052445 0.15149813 0.3410073 ] [0.29882132 0.91229046 0.48081166]


без numpy

In [ ]:
def scalar_product(a, b):
    if len(a) != len(b):
        raise ValueError("Длины векторы должны быть одинаковы")

    s = 0
    for x, y in zip(a, b):
        s += x * y
    return s

с numpy

In [ ]:
def np_scalar_product(a, b):
    s = np.dot(a, b)
    return s

In [ ]:
%time product_1 = scalar_product(a,b)
%time product_2 = np_scalar_product(a,b)
# проверим корректность:
np.abs(product_1 - product_2).sum()

CPU times: user 45 µs, sys: 0 ns, total: 45 µs
Wall time: 57.9 µs
CPU times: user 156 µs, sys: 0 ns, total: 156 µs
Wall time: 2.3 ms


0.0

Почему методы numpy оказываются эффективнее? Что вы можете сказать о скорости вычислений в NumPy?

Ответ: NumPy реализует множество оптимизированных алгоритмов для различных задач, включая скалярное произведение, NumPy обеспечивает эффективное управление памятью для больших массивов данных. Скорость вычислений в библиотеке numpy, связанных с массивами и матрицами довольно высока, это проиисходит благодаря вышеперечисленным пунктам.

Задание 3 Напишите функцию, которая находим сумму четных диагональныех элементов квадратной матрицы. Если таких элементов нет, то вывести 0.

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_diag_2k(a):
    diagonal_elements = np.diagonal(a)
    even_diagonal_elements = diagonal_elements[diagonal_elements % 2 == 0]
    res = even_diagonal_elements.sum() if even_diagonal_elements.size > 0 else 0
    return res

In [ ]:
# зададим некоторую квадратную матрицу
a = np.random.randint(1, 10, size=(5, 5))
a

array([[3, 9, 8, 7, 5],
       [9, 3, 2, 2, 8],
       [7, 3, 7, 1, 5],
       [4, 6, 8, 7, 9],
       [3, 7, 6, 2, 9]])

In [ ]:
%%time
# засечем время работы функции с NumPy
np_diag_2k(a)

CPU times: user 97 µs, sys: 14 µs, total: 111 µs
Wall time: 117 µs


0

Задание 4
На вход дан двумерный массив  X . Напишите функцию, которая для каждой строчки  x=(x1,x2,…,xn)  массива  X  строит строчку  s=(s1,s2,…,sn) , где  sk=x1+...+xkk , а затем выдаёт массив из построенных строчек. Используйте библиотеку numpy (вам поможет функция cumsum). Выходом функции должен быть двумерный массив той же формы, что и  X .

In [ ]:

import scipy.stats as sps

def np_sec_av(*A):
    stacked_arrays = np.vstack(A)
    sorted_rows = np.partition(stacked_arrays, 1, axis=1)
    second_largest_values = sorted_rows[:, 1]
    return second_largest_values

In [ ]:
# зададим некоторую последовательность и проверим ее на ваших функциях.
# функция должна работать ~ в 50 раз быстрее, чем без Numpy
A = sps.uniform.rvs(size=10**3)
print(A)

%time S2 = np_sec_av(A)

[0.03146942 0.46219825 0.033277   0.54907586 0.99185091 0.64345014
 0.07943498 0.12262199 0.92750272 0.88171262 0.79947899 0.63964151
 0.63510373 0.69579166 0.23629127 0.08775723 0.81757859 0.75003472
 0.55946618 0.11604402 0.70416826 0.38594886 0.69436805 0.22750263
 0.36078834 0.20111867 0.06444998 0.73465346 0.58329878 0.85732573
 0.33097409 0.39271432 0.71676839 0.26549636 0.10531308 0.55763608
 0.30243294 0.47232082 0.02909074 0.09044982 0.15226417 0.86173298
 0.02804003 0.6331498  0.6623985  0.81768995 0.13262337 0.57215907
 0.7592361  0.86159769 0.21125886 0.68303743 0.2632419  0.86417997
 0.70008166 0.02499819 0.88250722 0.72389025 0.16563127 0.945192
 0.98805492 0.7970507  0.64907217 0.10555899 0.68953028 0.29124631
 0.43802537 0.88542553 0.78052215 0.10409761 0.66584714 0.37999283
 0.89915766 0.85234718 0.85919244 0.30386282 0.61626535 0.69942346
 0.83983805 0.09788272 0.25436059 0.27515516 0.92093388 0.36285811
 0.78100609 0.40761072 0.41804611 0.62721288 0.06644466 0.696312

Задание 5
Написать функцию для кодирование массива (Run-length encoding). Все подряд повторения элементов функция сжимает в один элемент и считает количество повторений. Функция возвращает кортеж из двух векторов одинаковой длины. Первый содержит элементы, а второй — сколько раз их нужно повторить.

Пример: encode(np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])) = (np.array[1, 2, 3, 1, 5, 2, 3]), np.array[1, 2, 2, 2, 2, 1, 2])

In [ ]:
# функция, решающая задачу с помощью NumPy
def np_encode(a):
    if len(a) == 0:
        return np.array([]), np.array([])

    # Индексы, где происходит смена элементов
    change_indices = np.where(a[:-1] != a[1:])[0]

    # Добавляем индекс конечного элемента
    change_indices = np.concatenate(([0], change_indices + 1, [len(a)]))

    # Значения и их количество
    encoded_values = a[change_indices[:-1]]
    counts = np.diff(change_indices)

    result = encoded_values, counts
    return result


In [ ]:
from itertools import groupby
X = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])
%time x, num = np_encode(X)

CPU times: user 1.22 ms, sys: 0 ns, total: 1.22 ms
Wall time: 1.23 ms


Задание 6
Пусть задан некоторый одномерный массив  X . Надо построить новый массив, где все элементы с нечетными индексами требуется заменить на число  a  (если оно не указано, то на 1). Все элементы с четными индексами нужно возвести в куб. Затем записать элементы в обратном порядке относительно их позиций. Массив  X  при этом должен остаться без изменений. В конце требуется слить массив X с преобразованным X и вывести в обратном порядке.

In [ ]:
# функция, решающая задачу с помощью NumPy
import numpy as np

def np_transformation(X, a=1):
    result = np.copy(X)
    result[1::2] = a
    result[::2] **= 3
    result = np.concatenate((X, result[::-1]))
    return result




In [ ]:
X = np.array([i for i in range(1, 10, 2)])
# функция должна работать ~ в 20 раз быстрее, чем без Numpy
%time S2 = np_transformation(X, 5)

CPU times: user 108 µs, sys: 0 ns, total: 108 µs
Wall time: 113 µs
